language: node_js
node_js:
  - '4'
sudo: false
before_script:
  - env
  - ps auxf
  - hostname
  - uname -a
  - npm install -g protractor
script:
  - echo 'hello world again'
  - true
notifications:
  email:
    recipients:
      - $EMAIL
    on_success: always
    on_failure: always
